name: Demo
on: [push]

jobs: 
  frontend-workflow:
   name: FrontWorkflow
   runs-on: ubuntu-latest
  
   steps:
    - name: Check out repo code
      uses: actions/checkout@v2
     
    - name: Print  app.js
      run: cat src/frontend/app.js
     
     
