name: Übung2
on: [push]

jobs: 
  frontend-workflow:
    name: FrontWorkflow
    runs-on: ubuntu-latest
  
    steps:
    - name: Check out repo code
      uses: actions/checkout@v3

    - name: nodejs
      uses: actions/setup-node@v3.6.0
      with:
       node-version: 16

    
    - name: run app.js
      run: node src/frontend/app.js
    
    - name: directory
      run: mkdir -p dist
      
    - name: copying
      run: cp src/frontend/app.js dist/app.js
      
    - name: comment + date
      run : sed '1i // $now'
      
    - name: test
      run: node dist/app.js
      
    
